- name: install spreed (talk)
  args:
    chdir: /var/www/nextcloud/
  ansible.builtin.command: "sudo -u www-data php occ app:{{ item }}"
  with_items:
    - install spreed

- name: install coturn
  ansible.builtin.apt:
    update_cache: true
    state: latest
    name:
      - coturn

- name: ufw rules for coturn
  ansible.builtin.command: "{{ item }}"
  with_items:
    - ufw allow 3478/udp comment "incomming for coturn"
    - ufw allow 3478 comment "incomming for coturn"
    - ufw allow out 3478/udp comment "outgoing coturn"
    - ufw allow out 3478 comment "outgoing coturn"

- name: random coturn secret
  ansible.builtin.set_fact:
    coturn_secret: "{{ lookup('community.general.random_string', length=32, override_special=hex_chars) }}"
  vars:
    hex_chars: '0123456789abcdef'

- name: coturn config
  notify:
    - restart coturn
  ansible.builtin.copy:
    dest: /etc/turnserver.conf
    content: |
      listening-port=3478
      listening-ip={{ lookup('dig', nextcloud_fqdn, 'qtype=A') }}
      fingerprint
      use-auth-secret
      static-auth-secret={{ coturn_secret }}
      realm={{ nextcloud_fqdn }}
      total-quota=0
      bps-capacity=0
      no-tls
      no-dtls
      stale-nonce
      no-multicast-peers
      proc-user=turnserver
      proc-group=turnserver
      syslog

- name: enable turnserver
  ansible.builtin.lineinfile:
    name: /etc/default/coturn
    regexp: "#TURNSERVER_ENABLED=0"
    line: TURNSERVER_ENABLED=1

- name: enable coturn for talk
  args:
    chdir: /var/www/nextcloud/
  ansible.builtin.command: "sudo -u www-data php occ talk:turn:add turn {{ nextcloud_fqdn }} udp,tcp --secret={{ coturn_secret }}"
