- name: reload ufw
  community.general.ufw:
    state: reloaded

- name: restart caddy
  ansible.builtin.systemd:
    name: caddy
    daemon_reload: true
    state: restarted

- name: restart php-fpm
  ansible.builtin.systemd:
    name: php8.3-fpm
    state: restarted

- name: restart coturn
  ansible.builtin.systemd:
    name: coturn
    state: restarted

- name: restart mariadb
  ansible.builtin.systemd:
    name: mariadb
    state: restarted
